"""Compatibility facade for notebook websocket handlers.

This module keeps the historical import surface used by `backend/main.py`
while delegating implementations to split modules.
"""

from app.routers.notebook_common import (
    _parse_table_index,
    _get_kernel_lock,
    _timed_lock,
    active_tasks,
    cleanup_notebook_connection,
    jupyter_kernel_manager,
    manager,
    router,
    template_service,
    template_style_apply,
    template_table_format,
)
from app.routers.notebook_execution import (
    handle_cancel_code_execution,
    handle_code_execution,
    handle_force_reconvert_pdf,
    handle_notebook_attach_kernel,
    handle_notebook_create,
    handle_notebook_delete_cell,
    handle_notebook_execute_cell,
    handle_notebook_load,
    handle_notebook_move_cell,
    handle_notebook_save,
    handle_notebook_set_order,
    handle_reconvert_pdf,
)
from app.routers.notebook_kernel_control import (
    handle_notebook_cancel_execution,
    handle_notebook_comm_msg,
    handle_notebook_interrupt_kernel,
    handle_notebook_mdoc_clear,
    handle_notebook_reset_kernel,
    handle_notebook_shutdown_kernel,
)
from app.routers.notebook_template import (
    handle_template_apply_table_format,
    handle_template_attach,
    handle_template_create_style_from_table,
    handle_template_delete,
    handle_template_update_document_defaults,
    handle_template_get,
    handle_template_preview_cancel,
    handle_template_preview_style,
    handle_template_update_semantic_slots,
    handle_template_table_preview,
    handle_template_update_style,
    handle_template_upload,
)

__all__ = [
    "active_tasks",
    "cleanup_notebook_connection",
    "jupyter_kernel_manager",
    "manager",
    "handle_code_execution",
    "handle_cancel_code_execution",
    "handle_force_reconvert_pdf",
    "handle_notebook_attach_kernel",
    "handle_notebook_cancel_execution",
    "handle_notebook_comm_msg",
    "handle_notebook_create",
    "handle_notebook_delete_cell",
    "handle_notebook_execute_cell",
    "handle_notebook_interrupt_kernel",
    "handle_notebook_load",
    "handle_notebook_mdoc_clear",
    "handle_notebook_move_cell",
    "handle_notebook_reset_kernel",
    "handle_notebook_save",
    "handle_notebook_set_order",
    "handle_notebook_shutdown_kernel",
    "handle_reconvert_pdf",
    "handle_template_apply_table_format",
    "handle_template_attach",
    "handle_template_create_style_from_table",
    "handle_template_delete",
    "handle_template_update_document_defaults",
    "handle_template_get",
    "handle_template_preview_cancel",
    "handle_template_preview_style",
    "handle_template_update_semantic_slots",
    "handle_template_table_preview",
    "handle_template_update_style",
    "handle_template_upload",
    "template_style_apply",
    "template_service",
    "template_table_format",
    "_parse_table_index",
    "_get_kernel_lock",
    "_timed_lock",
    "router",
]
