"""Canonical Word/OOXML capability metadata for the Template Editor."""

from __future__ import annotations

import copy
from typing import Any, Dict, List


Capability = Dict[str, Any]

WORD_COMPLETE_CAPABILITIES: Dict[str, List[Capability]] = {
    "identity": [
        {
            "key": "style_id",
            "type": "string",
            "unit": None,
            "ooxml_target": "w:style/@w:styleId",
            "extraction": True,
            "application": False,
            "preview": False,
            "status": "readonly",
        },
        {
            "key": "display_name",
            "type": "string",
            "unit": None,
            "ooxml_target": "w:name/@w:val",
            "extraction": True,
            "application": False,
            "preview": False,
            "status": "readonly",
        },
        {
            "key": "based_on",
            "type": "style_ref",
            "unit": None,
            "ooxml_target": "w:basedOn/@w:val",
            "extraction": True,
            "application": True,
            "preview": False,
            "status": "supported",
        },
        {
            "key": "next",
            "type": "style_ref",
            "unit": None,
            "ooxml_target": "w:next/@w:val",
            "extraction": True,
            "application": True,
            "preview": False,
            "status": "supported",
        },
        {
            "key": "link",
            "type": "style_ref",
            "unit": None,
            "ooxml_target": "w:link/@w:val",
            "extraction": True,
            "application": True,
            "preview": False,
            "status": "supported",
        },
        {
            "key": "aliases",
            "type": "string_list",
            "unit": None,
            "ooxml_target": "w:aliases/@w:val",
            "extraction": True,
            "application": True,
            "preview": False,
            "status": "supported",
        },
        {
            "key": "ui_priority",
            "type": "integer",
            "unit": None,
            "ooxml_target": "w:uiPriority/@w:val",
            "extraction": True,
            "application": True,
            "preview": False,
            "status": "supported",
        },
        {
            "key": "default",
            "type": "boolean",
            "unit": None,
            "ooxml_target": "w:style/@w:default",
            "extraction": True,
            "application": False,
            "preview": False,
            "status": "readonly",
        },
        {
            "key": "custom",
            "type": "boolean",
            "unit": None,
            "ooxml_target": "w:style/@w:customStyle",
            "extraction": True,
            "application": False,
            "preview": False,
            "status": "readonly",
        },
        {
            "key": "locked",
            "type": "boolean",
            "unit": None,
            "ooxml_target": "w:locked",
            "extraction": True,
            "application": True,
            "preview": False,
            "status": "supported",
        },
        {
            "key": "auto_redefine",
            "type": "boolean",
            "unit": None,
            "ooxml_target": "w:autoRedefine",
            "extraction": True,
            "application": True,
            "preview": False,
            "status": "supported",
        },
        {
            "key": "rsid",
            "type": "hex",
            "unit": None,
            "ooxml_target": "w:rsid/@w:val",
            "extraction": True,
            "application": False,
            "preview": False,
            "status": "readonly",
        },
    ],
    "visibility": [
        {
            "key": "hidden",
            "type": "boolean",
            "unit": None,
            "ooxml_target": "w:hidden",
            "extraction": True,
            "application": True,
            "preview": False,
            "status": "supported",
        },
        {
            "key": "semi_hidden",
            "type": "boolean",
            "unit": None,
            "ooxml_target": "w:semiHidden",
            "extraction": True,
            "application": True,
            "preview": False,
            "status": "supported",
        },
        {
            "key": "q_format",
            "type": "boolean",
            "unit": None,
            "ooxml_target": "w:qFormat",
            "extraction": True,
            "application": True,
            "preview": False,
            "status": "supported",
        },
        {
            "key": "unhide_when_used",
            "type": "boolean",
            "unit": None,
            "ooxml_target": "w:unhideWhenUsed",
            "extraction": True,
            "application": True,
            "preview": False,
            "status": "supported",
        },
    ],
    "font": [
        {
            "key": "ascii_font_name",
            "type": "font_name",
            "unit": None,
            "ooxml_target": "w:rPr/w:rFonts/@w:ascii",
            "extraction": True,
            "application": True,
            "preview": True,
            "status": "supported",
        },
        {
            "key": "hansi_font_name",
            "type": "font_name",
            "unit": None,
            "ooxml_target": "w:rPr/w:rFonts/@w:hAnsi",
            "extraction": True,
            "application": True,
            "preview": True,
            "status": "supported",
        },
        {
            "key": "complex_script_font_name",
            "type": "font_name",
            "unit": None,
            "ooxml_target": "w:rPr/w:rFonts/@w:cs",
            "extraction": True,
            "application": True,
            "preview": False,
            "status": "supported",
        },
        {
            "key": "east_asia_font_name",
            "type": "font_name",
            "unit": None,
            "ooxml_target": "w:rPr/w:rFonts/@w:eastAsia",
            "extraction": True,
            "application": True,
            "preview": False,
            "status": "supported",
        },
        {
            "key": "theme_fonts",
            "type": "enum",
            "unit": None,
            "ooxml_target": "w:rPr/w:rFonts/@w:*Theme",
            "extraction": True,
            "application": True,
            "preview": True,
            "status": "supported",
        },
        {
            "key": "complex_script_size_pt",
            "type": "number",
            "unit": "pt",
            "ooxml_target": "w:rPr/w:szCs/@w:val",
            "extraction": True,
            "application": True,
            "preview": False,
            "status": "supported",
        },
        {
            "key": "character_spacing_twips",
            "type": "integer",
            "unit": "twips",
            "ooxml_target": "w:rPr/w:spacing/@w:val",
            "extraction": True,
            "application": True,
            "preview": False,
            "status": "supported",
        },
        {
            "key": "scale_percent",
            "type": "integer",
            "unit": "%",
            "ooxml_target": "w:rPr/w:w/@w:val",
            "extraction": True,
            "application": True,
            "preview": False,
            "status": "supported",
        },
        {
            "key": "kerning_pt",
            "type": "number",
            "unit": "pt",
            "ooxml_target": "w:rPr/w:kern/@w:val",
            "extraction": True,
            "application": True,
            "preview": False,
            "status": "supported",
        },
        {
            "key": "position_pt",
            "type": "number",
            "unit": "pt",
            "ooxml_target": "w:rPr/w:position/@w:val",
            "extraction": True,
            "application": True,
            "preview": False,
            "status": "supported",
        },
        {
            "key": "language",
            "type": "bcp47",
            "unit": None,
            "ooxml_target": "w:rPr/w:lang",
            "extraction": True,
            "application": True,
            "preview": False,
            "status": "supported",
        },
        {
            "key": "effects",
            "type": "boolean_set",
            "unit": None,
            "ooxml_target": "w:rPr/{bCs,iCs,vanish,shadow,outline,emboss,imprint,noProof,rtl,cs,specVanish,webHidden}",
            "extraction": True,
            "application": True,
            "preview": True,
            "status": "supported",
        },
    ],
    "paragraph": [
        {
            "key": "text_alignment",
            "type": "enum",
            "unit": None,
            "ooxml_target": "w:pPr/w:textAlignment/@w:val",
            "extraction": True,
            "application": True,
            "preview": False,
            "status": "supported",
        },
        {
            "key": "text_direction",
            "type": "enum",
            "unit": None,
            "ooxml_target": "w:pPr/w:textDirection/@w:val",
            "extraction": True,
            "application": True,
            "preview": False,
            "status": "supported",
        },
        {
            "key": "tabs",
            "type": "array",
            "unit": "twips",
            "ooxml_target": "w:pPr/w:tabs/w:tab",
            "extraction": True,
            "application": True,
            "preview": False,
            "status": "supported",
        },
        {
            "key": "borders",
            "type": "border_sides",
            "unit": "pt",
            "ooxml_target": "w:pPr/w:pBdr",
            "extraction": True,
            "application": True,
            "preview": False,
            "status": "supported",
        },
        {
            "key": "shading",
            "type": "shading",
            "unit": None,
            "ooxml_target": "w:pPr/w:shd",
            "extraction": True,
            "application": True,
            "preview": False,
            "status": "supported",
        },
        {
            "key": "pagination_and_layout_flags",
            "type": "boolean_set",
            "unit": None,
            "ooxml_target": "w:pPr/{contextualSpacing,mirrorIndents,suppressLineNumbers,suppressAutoHyphens,kinsoku,wordWrap,overflowPunct,topLinePunct,autoSpaceDE,autoSpaceDN,bidi,adjustRightInd,snapToGrid}",
            "extraction": True,
            "application": True,
            "preview": True,
            "status": "supported",
        },
    ],
    "lists": [
        {
            "key": "numPr",
            "type": "numbering_ref",
            "unit": None,
            "ooxml_target": "w:pPr/w:numPr + word/numbering.xml",
            "extraction": True,
            "application": True,
            "preview": True,
            "status": "supported",
        },
        {
            "key": "abstractNum",
            "type": "numbering_definition",
            "unit": None,
            "ooxml_target": "word/numbering.xml/w:abstractNum",
            "extraction": True,
            "application": False,
            "preview": True,
            "status": "readonly",
        },
    ],
    "table": [
        {
            "key": "tblPr",
            "type": "table_props",
            "unit": None,
            "ooxml_target": "w:style/w:tblPr",
            "extraction": True,
            "application": True,
            "preview": True,
            "status": "supported",
        },
        {
            "key": "tcPr",
            "type": "cell_props",
            "unit": None,
            "ooxml_target": "w:style/w:tcPr",
            "extraction": True,
            "application": True,
            "preview": True,
            "status": "supported",
        },
        {
            "key": "tblStylePr",
            "type": "conditional_table_style",
            "unit": None,
            "ooxml_target": "w:style/w:tblStylePr",
            "extraction": True,
            "application": True,
            "preview": True,
            "status": "supported",
        },
        {
            "key": "tblLook_tblW_tblLayout",
            "type": "runtime_defaults",
            "unit": None,
            "ooxml_target": "table_style_runtime_defaults",
            "extraction": True,
            "application": True,
            "preview": True,
            "status": "supported",
        },
    ],
    "globals": [
        {
            "key": "docDefaults",
            "type": "font_paragraph_defaults",
            "unit": None,
            "ooxml_target": "w:styles/w:docDefaults",
            "extraction": True,
            "application": True,
            "preview": True,
            "status": "supported",
        },
        {
            "key": "theme",
            "type": "theme",
            "unit": None,
            "ooxml_target": "word/theme/theme1.xml",
            "extraction": True,
            "application": False,
            "preview": True,
            "status": "readonly",
        },
        {
            "key": "font_table",
            "type": "font_table",
            "unit": None,
            "ooxml_target": "word/fontTable.xml",
            "extraction": True,
            "application": False,
            "preview": False,
            "status": "readonly",
        },
        {
            "key": "sections",
            "type": "section_props",
            "unit": "twips",
            "ooxml_target": "word/document.xml/w:sectPr",
            "extraction": True,
            "application": False,
            "preview": True,
            "status": "readonly",
        },
        {
            "key": "settings",
            "type": "settings",
            "unit": None,
            "ooxml_target": "word/settings.xml",
            "extraction": True,
            "application": False,
            "preview": False,
            "status": "readonly",
        },
    ],
    "raw": [
        {
            "key": "advanced_props",
            "type": "ooxml_node_lists",
            "unit": None,
            "ooxml_target": "rPr/pPr/tblPr/tcPr/tblStylePr replacement",
            "extraction": True,
            "application": True,
            "preview": False,
            "status": "raw_only",
        },
        {
            "key": "unsupported_nodes",
            "type": "json",
            "unit": None,
            "ooxml_target": "unknown/unsupported OOXML nodes",
            "extraction": True,
            "application": False,
            "preview": False,
            "status": "unsupported",
        },
    ],
}


RAW_ADVANCED_PROP_LIST_KEYS = frozenset({"r_pr", "p_pr", "tbl_pr", "tc_pr"})


def get_word_complete_capabilities() -> Dict[str, List[Capability]]:
    """Return a defensive copy of the Template Editor Word capability matrix."""
    return copy.deepcopy(WORD_COMPLETE_CAPABILITIES)


def validate_advanced_props_payload(advanced_props: Any) -> None:
    """Reject malformed raw OOXML replacement payloads before mutating DOCX parts."""
    if advanced_props in (None, ""):
        return
    if not isinstance(advanced_props, dict):
        raise ValueError("invalid_advanced_props: expected object")
    for key in RAW_ADVANCED_PROP_LIST_KEYS:
        if key in advanced_props and advanced_props.get(key) is not None and not isinstance(advanced_props.get(key), list):
            raise ValueError(f"invalid_advanced_props.{key}: expected list or null")
    if "tbl_style_pr" in advanced_props:
        value = advanced_props.get("tbl_style_pr")
        if value is not None and not isinstance(value, list):
            raise ValueError("invalid_advanced_props.tbl_style_pr: expected list or null")
        if isinstance(value, list):
            for index, entry in enumerate(value):
                if not isinstance(entry, dict):
                    raise ValueError(f"invalid_advanced_props.tbl_style_pr[{index}]: expected object")
                props = entry.get("properties")
                if props is not None and not isinstance(props, list):
                    raise ValueError(f"invalid_advanced_props.tbl_style_pr[{index}].properties: expected list")
